2024/12/02 04:21:40 [error] 6#6: *2 lua entry thread aborted: runtime error: init_worker_by_lua(nginx.conf:294):23: bad argument #2 to 'format' (number expected, got table)
stack traceback:
coroutine 0:
	[C]: in function 'format'
	init_worker_by_lua(nginx.conf:294):23: in function <init_worker_by_lua(nginx.conf:294):5>, context: ngx.timer
2024/12/02 04:28:57 [error] 13#13: *10 lua entry thread aborted: runtime error: init_worker_by_lua(nginx.conf:294):23: bad argument #2 to 'format' (number expected, got table)
stack traceback:
coroutine 0:
	[C]: in function 'format'
	init_worker_by_lua(nginx.conf:294):23: in function <init_worker_by_lua(nginx.conf:294):5>, context: ngx.timer
2024/12/02 05:40:09 [error] 7#7: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET /project/4/ HTTP/1.1", upstream: "http://192.168.10.24:6666/project/4/", host: "localhost:12345"
2024/12/02 05:40:10 [error] 7#7: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET /project/2/ HTTP/1.1", upstream: "http://192.168.10.24:6666/project/2/", host: "localhost:12345"
=== Testing log write access ===
2024/12/02 05:57:03 [error] 14#14: *1 [lua] init_worker_by_lua(nginx.conf:311):2: === Worker initialization started ===, context: init_worker_by_lua*
=== Testing log write access ===
2024/12/02 07:15:35 [error] 14#14: *1 [lua] init_worker_by_lua(nginx.conf:361):2: === Worker initialization started ===, context: init_worker_by_lua*
=== Testing log write access ===
2024/12/02 07:36:33 [error] 14#14: *1 [lua] init_worker_by_lua(nginx.conf:361):2: === Worker initialization started ===, context: init_worker_by_lua*
2024/12/02 07:57:29 [error] 14#14: *141 [lua] init_worker_by_lua(nginx.conf:361):89: Failed to create cleanup timer: process exiting, context: ngx.timer
